apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  selector:
    matchLabels:
      app: spring-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: icicipocacr001.azurecr.io/spring-demo:latest
        ports:
        - containerPort: 8090     
---
apiVersion: v1
kind: Service
metadata:
    name: spring-demo
spec:
    type: LoadBalancer
    ports:
    - port: 8090
    selector:
        app: spring-demo